name: Build Executable

on:
  push:
    paths:
      - "Event Management System/**"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        dir
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl

    - name: Clone Repository & Run Batch File
      run: |
        git config --global user.email "aznajhi97work@gmail.com"
        git config --global user.name "aznajhi"
        git clone https://${{ secrets.IV_TOKEN }}@github.com/AzNajhi/Mezza9-Solution.git 
        cd "Mezza9-Solution"
        dir
        build.bat
        dir

    - name: Push Executable File into Repository
      run: |
        cd "Mezza9-Solution"
        git status
        git add "Executable File/main.exe"
        git status
        git commit -m "Update Executable File"
        git status
        git pull origin main
        git push origin main
        
        
        

      
