name: Build Executable

on:
  push:
    paths:
      - "Event Management System/**"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout Repository
      run: |
        git clone https://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@github.com/AzNajhi/Mezza9-Solution.git 
        dir

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl

    - name: Run Batch File
      run: build.bat

    - name: Git Config
      run: | 
        git config --global user.name "aznajhi"
        git config --global user.email "aznajhi97work@gmail.com"
        git config --global --list

    - name: Push Executable File into Repository
      run: |
        del /q main.spec
        rmdir /s /q build
        ren dist "Executable File"
        git add "Executable File\main.exe"
        git commit -m "Update Executable File"
        git pull origin main
        git push origin main
        
        
        

      
