name: Build Executable

on:
  push:
    paths:
      - "Event Management System/**"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        dir
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl

    - name: Clone Repository & Run Batch File
      run: |
        echo git clone https://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@github.com/AzNajhi/Mezza9-Solution.git 
        cd "Mezza9-Solution"
        echo <Before Execute Batch File>
        dir
        build.bat
        echo <After Execute Batch File>
        dir

    - name: Push Executable File into Repository
      run: |
        cd "Mezza9-Solution"
        echo <Before Cleaning Up>
        dir
        del /q main.spec
        rmdir /s /q build
        ren dist "Executable File"
        echo <After Cleaning Up>
        dir
        git add "Executable File\main.exe"
        git commit -m "Update Executable File"
        git pull origin main
        git push origin main
        
        
        

      
