name: Build Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl

    - name: Run PyInstaller
      run: |
        pyinstaller --onefile `
           --hidden-import options `
           --hidden-import automated `
           --hidden-import manual `
           --hidden-import autotable `
           --hidden-import manualtable `
           --hidden-import autosave `
           --hidden-import mansave `
           "./Event Management System/main.py"
           
    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/main  # Adjust the path based on your PyInstaller setup
